name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  paths:
    - README.md

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2.1.0
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USER }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERHUB_REPOSITORY: danielhilpoltsteiner/adamo-nest-server
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Build the Docker image
  #     run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  #     - name: Docker Registry
  #     env:
  #       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  #       DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
  #       DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
  #     run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY_URL
        
  #   - name: docker push
  #     uses: actions/docker/cli@master
  #     with:
  #       args: push abhinavdhasmana/github-action-example-node
